### ISSUE TITLE
Cannot find module './webpack-pwa/dashboard/page'.

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack-pwa#2]
Go to admin - use the browser back button

<img width="826" alt="webpack_app" src="https://cloud.githubusercontent.com/assets/4113649/22424773/4e0a529c-e6f8-11e6-8371-669fdb7bc018.png">

**Comment by sokra** [comment]
It only worked when deployed on `/` because of a very simple way to extract page name from URL. I use an other way now.
