### ISSUE TITLE
build error `npm run build-shell`

### ISSUE THREAD

**Issue by kntmrkm** [webpack/webpack-pwa#7]
I got below error.

```
ERROR in afe436fe358f24997858.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [afe436fe358f24997858.js:27,65]

ERROR in 2b1b28982bbce9a8fb90.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [2b1b28982bbce9a8fb90.js:25,69]

ERROR in f57ea59692eeddb5f9ff.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [f57ea59692eeddb5f9ff.js:25,69]

ERROR in shell-5232f0bea5d8b88088f5.js from UglifyJs
SyntaxError: Unexpected character '`' [shell-5232f0bea5d8b88088f5.js:153,42]
```

<img width="877" alt="hyper" src="https://cloud.githubusercontent.com/assets/2703486/22649881/425d4198-ecc0-11e6-98ea-5b25f3f1090f.png">

My env is...

macOS 10.12.3

```
kntmrkm:~/code/javascript/webpack-pwa (master %=) $ npm -v
3.10.10
kntmrkm:~/code/javascript/webpack-pwa (master %=) $ node -v
v6.9.5
```

**Comment by sokra** [comment]
see https://github.com/webpack/webpack-pwa/issues/3#issuecomment-276145869

**Comment by addyosmani** [comment]
`npm i mishoo/UglifyJS2#harmony` fixed it for me too. I think this issue could be closed if that addresses it for you, @kntmrkm.

**Comment by kntmrkm** [comment]
@here 
thanks guys.

**Comment by fingerpich** [comment]
I have the same problem, I have done these steps
 - `clone the repo`
 - `npm install`
 - `npm i mishoo/UglifyJS2#harmony`
 - `npm run build-shell`

why it doesn't work for me?

**Comment by fingerpich** [comment]
Its fixed when I change them to 
```
    "uglify-js": "github:mishoo/UglifyJS2#harmony-v2.8.22",
    "webpack": "2.2.0",
```
